# This is a basic workflow to help you get started with Actions

name: build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Create Zip Archive

      run: zip -r "$REPO_NAME.zip" .
        env:
          # Název assetu na release
          asset_name: ${{ env.REPO_NAME }}.zip
          REPO_NAME: ${{ github.event.repository.name }}

      - name: Upload Release Asset
      id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }} # URL pro upload assetu
          asset_path: ${{ env.REPO_NAME }}.zip  # Cesta k zip souboru
          asset_name: ${{ env.REPO_NAME }}.zip  # Název assetu na release
          asset_content_type: application/zip
