name: build

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Create Zip Archive
        run: zip -r "$REPO_NAME.zip" .
        env:
          REPO_NAME: ${{ github.event.repository.name }}
           - name: Upload Artifact # Nahrazeno upload-artifact akcí
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.REPO_NAME }} # Název artefaktu
          path: ${{ env.REPO_NAME }}.zip # Cesta k zip souboru
